### ISSUE TITLE
app crashed if no github token

### ISSUE THREAD

**Issue by liul85** [dongyuwei/tagged-github-stars#2]
If you click `Login with Github personal token` without any token

![image](https://user-images.githubusercontent.com/1312723/86205282-cdd0be80-bbac-11ea-9cdd-d22ca3f45bca.png)

the app crashes
![image](https://user-images.githubusercontent.com/1312723/86205270-c3aec000-bbac-11ea-91e8-0d03148bd4e3.png)

app version: 0.2
macOS: 10.15.5

**Comment by dongyuwei** [comment]
谢谢亮仔报告问题。目前的错误处理基本都没有，都是 happy path。。
有空了完善一下。

**Comment by dongyuwei** [comment]
fixed in new release: https://github.com/dongyuwei/tagged-github-stars/releases/tag/v0.0.3

**Comment by liul85** [comment]
awesome!
