### ISSUE TITLE
Closed

### ISSUE THREAD

**Issue by h-jia** [dongyuwei/tagged-github-stars#4]
Closed

**Comment by dongyuwei** [comment]
Please try to delete your github token(named tagged-github-stars ) in Keychain.app

**Comment by h-jia** [comment]
Thanks. I renamed the key and seems can be reset now. 

BTW, to access the star, what scopes are needed to generate the token?

I select None/few/all scopes and could not find a solution to access the star, and it says: loading.

Thanks

![image](https://user-images.githubusercontent.com/29906369/94386270-90b7a080-018a-11eb-9510-19275f8aa83d.jpeg)

**Comment by h-jia** [comment]
Give in

**Comment by dongyuwei** [comment]
![Screenshot_2020-09-28-22-26-03-223_com android chrome](https://user-images.githubusercontent.com/112451/94445131-ac966300-01d9-11eb-8225-657e5de7a780.jpg)
